name: commons
description: A new Flutter package project.
version: 0.0.1
author: Toshi Ossada
homepage: https://www.ioasys.com.br/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  commons_dependencies:
    path: "../commons_dependencies"

dev_dependencies:
  build_runner: ^2.0.1
  flutter_modular_test: ^1.0.1
  hive_generator: ^1.1.0
  http_mock_adapter: ^0.2.1
  mockito: ^5.0.5
  triple_test: ^0.0.5  
  effective_dart: ^1.3.1

flutter:
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts/Rubik/Rubik-VariableFont_wght.ttf
        - asset: assets/fonts/Rubik/static/Rubik-Bold.ttf
          weight: 700
